import { commitTypes, type CometConfig } from "../domain/models.js";

export const defaultExcludeFiles = [
  ".env",
  ".env.local",
  ".env.*",
  "*.pem",
  "*.key",
  "*.crt",
  "*.p12",
  "*.pfx",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  "composer.lock",
  "Cargo.lock",
  "dist/**",
  "build/**",
  ".next/**",
  "node_modules/**",
  "vendor/**",
  "coverage/**",
];

export const defaultConfig: CometConfig = {
  provider: "openai",
  model: "gpt-4o-mini",
  baseUrl: null,
  apiKey: null,
  customHeaders: null,
  promptModule: "conventional-commit",
  language: "en",
  uiMode: "minimal",
  description: true,
  emoji: false,
  oneLine: false,
  omitScope: false,
  why: false,
  messageTemplate: "$msg",
  maxInputTokens: 12000,
  maxOutputTokens: 1024,
  autoCommit: false,
  gitPush: false,
  stageAll: false,
  redactSecrets: true,
  privacyMode: "standard",
  excludeFiles: defaultExcludeFiles,
  policyAllowedTypes: [...commitTypes],
  policyRequireIssueKey: false,
  issueKeyPattern: "[A-Z][A-Z0-9]+-\\d+",
  policyScopeMap: null,
  showCopilot: false,
  showSplitPlan: false,
  showSafeSend: false,
  showAnalysis: false,
  showQuality: false,
  showWarnings: false,
  allowSplitSuggestions: true,
  allowSplitExecution: true,
  verbose: false,
};
